title: Meryem Essaidi
author: 35 Olden St, Princeton
author: NJ 08540
email: messaidi@princeton.edu 
email: essaidi.meryem@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
  
# social links
# dribbble_username: jekyll
# facebook_username: jekyll
linkedin_username: meryem-essaidi-2414698b
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag