title: Meryem Essaidi
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "twitter_username:"




# social links
github_username:  messaidi
linkedin_username: meryem-essaidi
googleplus_username: +jekyll



show_excerpts: true # set to true to show excerpts on the homepage


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.md

# Build settings
# theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag