title: Meryem Essaidi
author: 35 Olden St, Princeton, NJ 08540
email: messaidi@princeton.edu

  

# social links
linkedin_username: 
[LinkedIn](https://www.linkedin.com/in/meryem-essaidi-2414698b)


show_excerpts: false # set to true to show excerpts on the homepage


# Build settings
theme: minima


